# Generated by Django 3.0.3 on 2020-02-17 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20200217_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advert',
            old_name='creator_id',
            new_name='creator',
        ),
    ]
